README.rst
schema.py
test_schema.py

This lets us insert default values for missing dict keys. I independently arrived at this API before seeing that it's also a leading contender in https://github.com/keleshev/schema/pull/19, so it's at least unsurprising for 2 people. :-)
I had to do a minor twiddle of prioritization so that more generic keys like `str` wouldn't eat the Optionals' lunch, but that shouldn't affect any conceivable non-crashing use case. (See one of the commit messages for details.)

Support defaults via Optional

---

setup.py

If LANG was not set on python3, opening this file (which happens when
installing) would fail because the README.rst contains non-ascii
characters. Using `codecs` we can explicitly decode it as utf-8.
Fixes #68

setup.py: Decode README.rst as utf-8

---

schema.py
test_schema.py

Fix reliance on `__name__` of callables, fixes #56

---

schema.py

Currently when you install the latest development version via
e.g. pip install 'git+https://github.com/keleshev/schema.git'
you end up with a schema package that still advertises itself
as version 0.3.1, even though it's a later version.
Bumping the version to 0.3.2.dev0 makes it easier for users
to confirm whether a bug released in 0.3.1 has since been
fixed in master, as we can now inspect `schema.__version__`
and get a different value than the version with the bug.
I learned it's good practice to bump the version like this as the
next commit to master immediately after doing a release.

bump version to 0.3.2.dev0 as 0.3.1 was released long ago

---

README.rst
schema.py
test_schema.py

To avoid `SchemaError` for validations with more keys of the schema:
```python
>>> Schema({'key', 'value'}, strict=False).validate({'key', 'value', 'foo': 'bar})
>>> {'key', 'value'}
```

add strict flag in Schema class to skip wrong key validation without wildcard

---

README.rst
schema.py
test_schema.py

Hi,
Here is a proposition to add regex support to the library, with the use of `re.pattern.search` method from the Python core regex library (support was tested on python 2.6.9, 2.7.12, 3.3.0, 3.4.3, 3.5.2, pypy-5.3 and pypy3-2.4.0).
Four simple test cases were added as well.
Note that support for python 3.2 was not tested because of an issue with tox and virtualenv: https://github.com/travis-ci/travis-ci/issues/5517

Adding regular expression (regex) support

---

schema.py

This PR adds a call to format on the `error` parameter before displaying it, passing the data into the formatter. This allows custom error messages to change from something like `"Invalid user id."` to `"Invalid user id: {}"`, which would display as `"Invalid user id: 9243"`.
Please let me know if I missed something somewhere.

Allow the error parameter string to contain string formatting parameters

---

schema.py

Wrong keys are sorted, but for some reason, missing keys are not.
Sorting them in the error message looks better and is useful for testability.

Sort missing keys

---

README.rst
schema.py
test_schema.py

I added a key error because if a dict is huge, it's hard to find what key error happen

Show a key error if a dict error happens

---

schema.py
test_schema.py

Hi nice to meet you!
I love your python library, which is small but powerful 😄 
But I have a case to convert data before validating.
When I tried override `validate` method of `Schema`, I found the `Schema` in `And` and `Or` class need to be changed.
I am happy if you merge this commit or give me some advice 😄 
Thanks!

Schema can be inherited

---

README.rst

Tox file has py34 and py35, and Travis CI confirms latest master is being tested with them and passing the tests.

Added py34 and py35 to "tested with" on Readme

---

schema.py

In Python 3, when assign an exception instance (i.e. _x) to different name (i.e. x) in a local scope, 
A traceback object created and the tb_frame attribute of it refer to the frame of this scope.
Here's an example that demonstrate the issue:
```
>>> import sys
>>> from schema import And, Or, Schema, SchemaError
>>>
>>> s = Schema(And(Or(int, float), lambda x: x > 0))
>>> sys.getrefcount(s)
2
>>> # Or's 1st argument - exception instance (i.e. _x) is not assigned to local name (i.e.  x)
>>> s.validate(10)  
10
>>> sys.getrefcount(s)
2
>>> # Or's 2nd argument - exception instance (i.e. _x) assigned to local name (i.e.  x).
>>> s.validate(3.1415)  
3.1415
>>> sys.getrefcount(s)
3
>>> try:
...      s.validate('10') 
... except SchemaError as e:
...      print(e)
Or(<class 'int'>, <class …
```

Fix reference count issue for Or's objects.

---

test_schema.py

With PyPy (at least version 2.7.3), methodcaller generated callables do have a __name__ attribute, so _callable_str() will not attempt to stringify it making this unit fail.

Fix callable check under PyPy2

---

schema.py

Originated from the issue #134 
Description:
This methods returns True if the given data has passed all the validations that were specified in the given schema, returns false if not.
Considerations:
This method doesn't raise any exception and thus prevent any exception from the schema validation to pass silently

creating is_valid method as suggested in the issue 134

---

schema.py

Fix typo in schema.py: `vaidated` -> `validated`

Fix typo in schema.py: vaidated->validated

---

schema.py

[`assert` statements are bypassed](https://stackoverflow.com/questions/1273211/disable-assertions-in-python) when running in "optimized" mode (i.e. `python -O`).
`assert` should only be used in tests or for debug output.

Remove Assert Statements

---

README.rst
schema.py
test_schema.py
tox.ini

* Add Hook class that allows custom handlers
* Make Forbidden a subclass of Hook that raises an exception as its handler
* My personal use case for this, creating a Deprecated hook that will be called that way: `Deprecated("attribute")`. My handler will simply be a function that logs a warning to the user when he uses that attribute. I am sure there are other use cases for a custom handler class.
Let me know what you think!

Add Hook class. Allows to introduce custom handlers

---

README.rst
schema.py
test_schema.py

Fixes #106 
It's a bit sad that `Schema` has to know that `Or` has a `reset()` method but `Schema` has to know when to reset. Otherwise, subsequent `validate` calls of the same schema with the same value will fail. 
The other thing I considered is to subclass all the validators with a base class with an empty `reset()` method and always call it, `Or` would have overridden that method.
Let me know what you think!

Allow exclusive or in a dict schema

---

schema.py
test_schema.py

This fixes an issue in https://github.com/keleshev/schema/pull/174. When Or was Optional, the reset method was not called

Fix Or reset() when Or is Optional

---

.travis.yml
tox.ini

Note:
- Travis CI requires `dist: xenial` + `sudo: true` for python 3.7 (https://github.com/travis-ci/travis-ci/issues/9815). These statements can be removed once they move to xenial by default
- For some reason my pep8 build is using pyflakes 2.0.0 which is performing W504 check by default, which would cause errors in `schema.py`. I suppressed that warning in tox.ini instead.

Travis CI python 3.7

---

README.rst
schema.py
test_schema.py

Big-ish PR but the title is self explanatory. Implementation of draft-7 json schema generation: https://json-schema.org/.
Some caveats:
- Some types are not handled. In that case, the `{}` dict is returned (no checks in that case)
- There are no object references, objects are always fully rendered
- Also there may be other features of JSON Schema that I did not implement (because I'm not aware of them :smile: )
- I tested it with a very large schema, and all of it works. I'd love to see some use cases that I did not think of though
- I did not do any documentation, if we do any, it should probably be noted that this is a beta feature. And I wanted to have your opinion on this feature before writing any of it.
Let me know what you think!

Generate JSON schema from schema

---

schema.py
test_schema.py

Also added a new test case for covering the plural case of SchemaMissingKeyError.

Use correct singular/plural form of “key(s)” in error messages

---

README.rst
schema.py

allow optional to take a callable as default  (dict or list for example)

allow Optional(..., default=obj) to be a callable

---

README.rst
schema.py
setup.py
test_schema.py

This is adding on top of #180 
New features are:
- Regular expressions (e.g. `Regex("^something-.*")` will generate `{"type": "string", "pattern": "^something-.*"}`)
- const (e.g. `[1]` will generate `{"const": 1}`)
- enum (e.g. `["foo", "bar"]` will generate `{"enum": ["foo", "bar"]}`)
- And (e.g. `And(str, "test2")` will generate `{"allOf": [{"type": "string"}, {"const": "test2"}]}`)
I've also added the title of the source Schema in the generated JSON schema.

Improve JSON schema generation

---

README.rst

I think this might make the readme render properly on PyPI
Before this fix, Sphinx says: "WARNING: Error in "code" directive: maximum 1 argument(s) allowed, 18 supplied."

Fix error in README.rst

---

README.rst
schema.py
test_schema.py

To reduce the size of the generated JSON schema, this PR adds setting an id for a part of the schema and then using the id as reference in other parts.
For our particular use case, the produced JSON schema decreased size from 54 MiB to 65 KiB using this feature.
Some caveats:
- The resulting schema is not the smallest it can be because of the way the tree is traversed. I tested different approaches to reduce it further, but thought that the added complexity and execution time was not worth the size reduction. In my above example, the size went down to 28 KiB with breadth-first traversal instead of 65 KiB with the implementation in this PR, still not a significant gain from the 54 MiB when not using references.
- This produces a single schema, not several files with references, [as is …

Add references to JSON schema rendering

---

schema.py
test_schema.py

Fixes a bug introduced by #208.
The Literal type could not be rendered in JSON because it could not be cast to string. Moreover, the implementation of Or assumed the keys were string, but they could be Literal.
Sorry for the bug!

JSON Schema: Fix using Literal in enum

---

README.rst
schema.py
test_schema.py

Yet another JSON schema PR!
This one let users give a name to a part of their schema and use it as a reference. I was not satisfied with the previous implementation that would compute hashes and create a schema that is hard to read by humans. It was also not compatible with all IDEs. This is explained here: https://json-schema.org/understanding-json-schema/structuring.html#reuse
I also added a lot more information and exemples in the README, now every JSON schema feature is explained. Tell me if you think this could be improved.
By using this along with [docson](https://github.com/lbovet/docson) we now have a configuration schema that is light, works with most IDEs and is automatically documented.

JSON schema with common definitions + Update README

---

README.rst
schema.py
test_schema.py

I forgot to handle the "dict" type which would result in JSON schemas with "string" instead of "object" for parameters that are of the dict type, but that doesn't have keys specified.

JSON Schema: Fix using `dict` as type

---

README.rst

Hi @keleshev ,
I'm very grateful for this lib. It's one of my favorite python packages - lightweight and speedy.
It seems like everything except for pre-commit `black` formatting is covered for `py37`, and it's definitely tested with 3.7.  Although I verified py37 so I can use on a current 3.7 project, it would be great if it were in the README. If there's a specific reason 3.7 isn't listed that's understandable.
Thanks again for the awesome library!

README: add 3.7 to list of tested versions

---

schema.py
test_schema.py

Reading [the Reuse section of Understanding JSON Schema](https://json-schema.org/understanding-json-schema/structuring.html#reuse), I notice there should be nothing other than `$ref` when reusing another section of the schema.
This fixes the library behavior by adding the description on the referenced element instead.

JSON Schema: Don't add a description in a ref

---

schema.py
test_schema.py

When using Optional as a key, a default value can be set. With this change, the default value will be added to the generated JSON schema as well.

JSON Schema: Include default values

---

requirements.txt

0.5.5 is not the latest version any more.

Relax contextlib2 requirement

---

.travis.yml
setup.py
tox.ini

The tags sudo and matrix are now deprecated and removed from Travis CI documentation.

Travis CI: Add Python 3.8 to the testing

---

schema.py
test_schema.py

Starting with draft-04, the JSON schema specification allows having other attributes next to `$ref`. This is useful for us when using descriptions, because we may want to use a different description depending on where the sub schema is used.
Descriptions from `Literal` used as keys were already added to the value it references. With this change, descriptions will be added alongside the $ref node if the value is another schema and that schema has `as_reference` set to True.
For an example, look at `test_json_schema_definitions_and_literals`.

JSON Schema: Add description next to $ref

---

README.rst
schema.py
tox.ini

When raising a SchemaError with a user readable error message this message would
be dropped if there was more than one validator in an Or() clause.
BTW: Thanks for the library, we use it extensively to keep our model correct.

Do not drop previous errors within an Or criterion.

---

README.rst
schema.py
test_schema.py

The first version of the JSON Schema generation feature did not accept having any types other than a dict for the root.
This means that calling `json_schema` on `Schema({"test": [1, 2, 3]})` would work but on `Schema([1, 2, 3])`, it would just return the error "The main schema must be a dict."
After testing, turns out this was an artificial limitation and nearly no code change is needed to have it work with any supported types.
This will also make the examples in the README actually work :)

JSON Schema: Support schemas where the root is not a dict

---

schema.py

There is a feature (although not documented and not tested) that allows passing format strings as error messages to the validators, which format them with the validated data if a `SchemaError` is thrown.
I find this feature very useful, but it does not work when validating using a callable.
For example, with the current behavior: `schema.Schema(lambda d: False, error='{}').validate('This should be the error message')` -> `SchemaError: {}`
After the fix, the error will be `SchemaError: This should be the error message`

Fix error formatting for validation with callable

---

README.rst

Noticed a minor typo in a code example on README for creating a json schema for `"allOf"`
- Original: `Schema(And(str, "value")` _<- missing closing_ **`)`**
- Updated: `Schema(And(str, "value"))`

minor > fix typo in allOf example

---

README.rst
schema.py
test_schema.py

When a dict has a `str` or `object` as one of its keys, `schema` is accepting extra keys (or additional properties in JSON schema language). However, the generated JSON schema will have `additionalPropeties` set to False.
Currently, the only way to have `additionalPropeties` set to true is to use `ignore_extra_keys` in the `Schema` object constructor. Users may not want to do that because that means that `validate` will not include the keys in the result.
This fix will have `additionalPropeties` set to true if `ignore_extra_keys` is True or if any of the key is `str` or `object` (or `Optional(str)` or `Optional(object)`).

JSON Schema: Set additionalProperties true when dict contains str as key

---

schema.py
test_schema.py

Similarly to #243, using `as_reference` only worked when the schema is an object (dict).
This change seems longer than it is, it is mainly just moving code. The part creating a $ref object has been moved to before checking the flavor, instead of being inside the `flavor == DICT` section.

fix: JSON Schema: Allow using $ref when schema is not a dict

---

schema.py

On Python 3.8.6, we have started getting this weird error:
```ValueError: Unknown format code 'b' for object of type 'str'```
Turns out there was a change in Python itself so that it is not possible to use a format string with a `RegexFlag` object anymore.
Casting to int resolves the issue while keeping compatibility with older Python versions.

Fix "Unknown format code" in Python 3.8

---

schema.py
test_schema.py

Pull request #238 introduced a change (which was released in 0.7.3) which
caused errors to sometimes be formatted twice, which caused valid data to
sometimes appear to be invalid, as described in issue #240.
This commit reverts pull request #238, which fixes issue #240, and also adds
error formatting to some other exceptions including the one which gets raised
in the example described as motivation for the change in #238.
It also adds test cases to ensure the behaviors desired in both #238 and #240
remain present.
This commit is also relevant to anyone looking at issue #241 (though it does
not implement the plan described there).

don't double-format errors. fixes #240

---

README.rst

In the tox.ini you are testing against many versions including python3.8 and python3.9.
Add them to the README.
Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

Add python3.8/3.9 to the README as tested

---

test_schema.py

Since Python 3.3 unittest.mock is available as a build in module.
Tox still mentions mock, but I have no idea how to make that optional.

Make mock test dependency optional for Python > 3.3

---

requirements.txt

`contextlib.ExitStack` was added in Python 3.3

only require contextlib2 on Python < 3.3

---

schema/__init__.py
test_schema.py

- feat: [JSON Schema] Add title for Literal
- fix: [JSON Schema] attempt to make regexes ECMA-compliant
- fix: [JSON Schema] Use "type": "null" instead of "const": "null"

JSON Schema: Add title for Literal, ECMA regexes, and null type in const

---

schema/__init__.py
test_schema.py

Fixing [my last PR ](https://github.com/keleshev/schema/pull/330)
It's
```json
{
"type": "null"
}
```
not
```json
{
"type": null
}
```
Also fix the name of a unit test I accidently changed
Sorry for the troubles

fix: [JSON Schema] Type "null" should be string

---

schema/__init__.py
test_schema.py

The `name` attribute of `Schema` is used for the JSON Schema's title attribute, but it does not work on schemas used as reference or used as elements of `Or`, `And` , etc.
Example:
```python
Schema(
{
"test": Or(
Schema(
"option1", name="Option 1", description="This is the first option"
),
Schema(
"option2",
name="Option 2",
description="This is the second option",
),
)
}
)
```
Before:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"$id": "my-id",
"properties": {
"test": {
"anyOf": [
{
"const": "option1",
"description": "This is the first option",
},
{
"const": "option2",
"description": "This is the second option",
},
]
}
},
"required": ["test"],
"additionalProperties": false,
"type": "object",
}
```
After:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#", …
```

fix: JSON Schema missing title in subschemas
