keleshev/schema

README.rst
Small fix in documentation that makes tests pass.
=> fix README.rst doctest

setup.py
As Travis won't yet run Python3.5 with tox, I've tested this locally.
=> Add Python3.4 and 3.5 to setup.py

schema.py, test_schema.py
=> Iterable validation: Let the input type determine the return type

schema.py
Due to a small [communication hickup](https://github.com/keleshev/schema/pull/95#discussion_r42007338).
=> Simplify sorting of schema keys

schema.py
As [requested](https://github.com/keleshev/schema/issues/59#issuecomment-148041390).
=> Clean up module namespace

schema.py
Notice that the tests were failing would be good if we could include this feature in the next release.
=> Fixing failing tests for error formatting feature. (#98)

README.rst, schema.py, test_schema.py
Adding SchemaError SubClass: SchemaWrongKey, SchemaMissingKeyError and SchemaUnexpectedError (#111)
=> Adding SchemaError SubClass: SchemaWrongKey, SchemaMissingKeyError (#111)

schema.py
I have been looking at the code in more details and took advantage to add docstrings to the code base and reduce the character length to 79 characters as per PEP8 conventions.
=> Adding docstrings and reflowing code to maximum 79 characters PEP8.

schema.py
=> Making errors argument optionnal

test_schema.py
=> Adding serialization test

schema.py
I tend to do `from schema import *`, didn't initially
understand why Use didn't want to come :)
=> Add 'Use' to schema.__all__

schema.py, test_schema.py
=> Apply ignore flag recursively for dict

schema.py, test_schema.py
change to unit test as requested (new PR to keep history clean)
=> added __hash__ and __eq__ based on sub-schema to Optional

README.rst, schema.py, test_schema.py
See the documentation and inline comments for more details.
=> Implement Forbidden.

.travis.yml, README.rst, schema.py, test_schema.py
please take a look in `test_schema.py` to see use case example for `Const`.
=> Implement Const validator to keep data unchanged

.gitignore, .travis.yml, README.rst, setup.py, tox.ini
Tests look green on my local machine, I think it'd be a good idea to add it to the supported Python versions.
=> Added Py36 support

tox.ini
force python 2 for the coverage check
=> use python 2 for the coverage report

schema.py, test_schema.py
There's actually 2 different fixes here
First, default values were not added to the JSON Schema if they were falsy (`None`, `False`, `[]`, `{}`, `0` are correct default values). Since `key.default` is not set on `Optional` if it has no default, there was no need to check the value anyway.
When fixing that, I found a bigger problem. Values used in both `const` and `default` were simply cast to string. You would end up with
```json
{
"const": "None"
}
```
instead of
```json
{
"const": null
}
```
It will now make an attempt to convert the value to a JSON serializable type but fallback to casting as a string.
=> JSON Schema: Fix using falsy values as default

README.rst
The added newline is required in order to render the code block, currently it is hidden.
=> fix readme code block typo

schema.py, test_schema.py
Fixes an issue raised while investigation #219
=> JSON Schema: Fix allOf and oneOf with only one condition

README.rst
=> Fix README for Enums

schema.py
Hello,
As part of a coding dojo we organized in our team, we took the opportunity to see what could be improved in this library (which is really nice by the way!). Here, we just slightly improved Or class comment.
Cheers,
Julien
=> Improved Or class comment to document only_one purpose.

schema.py
Hello,
As part of a coding dojo we organized in our team, we took the opportunity to see what could be improved in this library (which is really nice by the way!).
Here is our humble result of 4 people spending two hours of code-reading, playing around and searching for stuff to improve.
Basically we:
- Simplified And.__init__, usage of **kwargs was not needed.
- Extracted _build_schema and _build_schemas from And.validate.
- Adapted Or.validate to rely on _build_schema and _build_schemas.
Cheers,
Julien
=> Refactored And and Or classes to make them more readable.

README.rst
Some of the code examples were extremely hard to read.
For the most part I just used black to format them, except in the smaller examples, in which I put the curly braces and parenthesis on the same line to make it a bit more compact.
For the first example I omitted the `>>>` and `...` characters to make it easier to copy and paste it to try it locally.
=> Readme code samples readability

MANIFEST.in
Fixes  #313 (untested, because I'm not sure how the sdist is created for this project).
=> build: Add tox.ini to sdist

setup.py
Related to
https://github.com/keleshev/schema/issues/318
, in my opinion this is safer than an eval call.
=> More straightforward way to retrieve the current version number
